### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by rickmed** [abrahamjagadeesh/npm-module-stats#1]
./node_modules/.bin/npm-module-stats --name=jest       

               
/usr/bin/env: ‘node\r’: No such file or directory

**Comment by vish288** [comment]
Similar to [this](https://github.com/nwjs/nw-builder/issues/75). I think this needs the files to be standardized in encoding before the files to be pushed.

Please take a look at [this](https://github.com/nwjs/nw-builder/issues/75#issuecomment-55516010) and add the git attributes to the project.

@abrahamjagadeesh

**Comment by abrjagad** [comment]
Fixed in v0.0.7
