### ISSUE TITLE
production package only?

### ISSUE THREAD

**Issue by kwonoj** [abrahamjagadeesh/npm-module-stats#3]
Hi, maybe I'm missing how to use this - please allow me question. If you'd like to calculate only production pkgs, is there command args to do it?

**Comment by abrjagad** [comment]
Could you elaborate?

**Comment by kwonoj** [comment]
Sure, what I meant is let's say if you have `package.json` with

```js
dependencies: {
 a:'0.0.x'
 b:'0.0.x'
},
optionalDependencies: {
 d: '0.0.x'
},
devDependencies: {
 c: '0.0.x'
}
```

and get size of dependencies only for `a,b,d` while excluding `c`, which doesn't being installed in production and does not need to calculate its size. By just reading readme in repo, not sure if this is already supported.

**Comment by abrjagad** [comment]
By default, it calculates only production modules.
